# Generated by Django 4.2.7 on 2025-04-11 13:58

import apps.competition.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newentries_Opendate', models.DateField(db_column='newentries_Opendate', verbose_name='Opening date for entries')),
                ('newentries_Closedate', models.DateField(db_column='newentries_Closedate', verbose_name='Closing date for entries')),
                ('admin_emailaddress', models.CharField(max_length=30, verbose_name='Admin email address')),
                ('num_schoolcandidate_scores', models.IntegerField(db_column='num_schoolcandidate_scores', null=True, verbose_name='Number of school candidate scores')),
                ('number_of_individuals', models.IntegerField(db_column='num_individuals', verbose_name='Maximum individual entries per grade per school')),
                ('number_of_pairs', models.IntegerField(db_column='num_pairs', verbose_name='Maximum pair entries per grade per school')),
                ('prizegiving_date', models.DateField(db_column='prizegiving_date', verbose_name='Prize-giving date')),
                ('invigilators', models.BooleanField(db_column='invigilators', default=False, verbose_name='Require schools to provide invigilators')),
                ('answer_sheet_download_enabled', models.BooleanField(db_column='answer_sheet_download_enabled', default=False, verbose_name='Allow teachers to download answer sheets')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255, verbose_name='School name')),
                ('key', models.CharField(db_column='Key', max_length=3, unique=True)),
                ('language', models.CharField(choices=[('e', 'English'), ('a', 'Afrikaans'), ('b', 'Bilingual')], db_column='Language', max_length=1)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=15)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=255)),
                ('entered', models.IntegerField(db_column='Entered', null=True)),
                ('score', models.IntegerField(blank=True, db_column='Score', editable=False, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', editable=False, null=True)),
                ('location', models.CharField(choices=[('CPT', 'Cape Town'), ('GEO', 'George')], db_column='Location', max_length=3)),
                ('answer_sheets_emailed', models.DateTimeField(blank=True, db_column='answer_sheets_emailed', default=None, null=True, verbose_name='Answer sheets emailed to teacher')),
                ('report_emailed', models.DateTimeField(blank=True, db_column='report_emailed', default=None, null=True, verbose_name='Results report emailed to teacher')),
                ('assigned_to', models.ForeignKey(blank=True, db_column='Assigned to', default=None, null=True, on_delete=apps.competition.models._on_delete, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=31, unique=True)),
                ('building', models.CharField(db_column='Building', max_length=40)),
                ('seats', models.IntegerField(db_column='Seats')),
                ('grade', models.IntegerField(blank=True, choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], db_column='Grade', null=True)),
                ('allocated_to_pairs', models.BooleanField(db_column='Allocated to PAIRS', default=False)),
                ('occupied_seats', models.IntegerField(blank=True, db_column='Occupied seats', editable=False, null=True)),
                ('location', models.CharField(choices=[('CPT', 'Cape Town'), ('GEO', 'George')], db_column='Location', max_length=3)),
            ],
            options={
                'ordering': ['building', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStudentArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateField(blank=True, db_column='Date Archived', null=True)),
                ('firstname', models.CharField(db_column='First_name', max_length=255, verbose_name='First name')),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('language', models.CharField(choices=[('e', 'English'), ('a', 'Afrikaans'), ('b', 'Bilingual')], db_column='Language', max_length=1)),
                ('reference', models.CharField(db_column='Reference', max_length=7)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('grade', models.IntegerField(db_column='Grade', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(8)])),
                ('venue', models.CharField(blank=True, db_column='Venue', max_length=40)),
                ('paired', models.BooleanField(db_column='Paired', default=False)),
                ('location', models.CharField(choices=[('CPT', 'Cape Town'), ('GEO', 'George')], db_column='Location', max_length=3)),
                ('school', models.ForeignKey(db_column='School', on_delete=apps.competition.models._on_delete, to='competition.school')),
            ],
            options={
                'ordering': ['archived', 'grade', 'surname', 'firstname', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='First_name', max_length=255, verbose_name='First name')),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('language', models.CharField(choices=[('e', 'English'), ('a', 'Afrikaans'), ('b', 'Bilingual')], db_column='Language', max_length=1)),
                ('reference', models.CharField(db_column='Reference', max_length=7)),
                ('score', models.IntegerField(blank=True, db_column='Score', editable=False, null=True)),
                ('rank', models.IntegerField(blank=True, db_column='Rank', editable=False, null=True)),
                ('grade', models.IntegerField(db_column='Grade', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(8)])),
                ('venue', models.CharField(blank=True, db_column='Venue', max_length=40)),
                ('paired', models.BooleanField(db_column='Paired', default=False)),
                ('award', models.CharField(blank=True, db_column='Award', editable=False, max_length=3, null=True)),
                ('location', models.CharField(choices=[('CPT', 'Cape Town'), ('GEO', 'George')], db_column='Location', max_length=3)),
                ('school', models.ForeignKey(db_column='School', on_delete=apps.competition.models._on_delete, to='competition.school')),
            ],
            options={
                'ordering': ['school', 'grade', 'surname', 'firstname', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibleTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='First_name', max_length=255, verbose_name='First name')),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('phone_primary', models.CharField(blank=True, db_column='Phone (Primary)', max_length=15)),
                ('phone_alt', models.CharField(blank=True, db_column='Phone (Alternative)', max_length=15)),
                ('phone_cell', models.CharField(blank=True, db_column='Cellphone', max_length=15)),
                ('email_school', models.CharField(db_column='Email (School)', max_length=50)),
                ('email_personal', models.CharField(blank=True, db_column='Email (Personal)', max_length=50)),
                ('is_primary', models.BooleanField(db_column='Is_primary', default='true')),
                ('report_downloaded', models.DateTimeField(blank=True, db_column='Report_downloaded', null=True, verbose_name='Results report downloaded manually by teacher')),
                ('answer_sheet_downloaded', models.DateTimeField(blank=True, db_column='Answer_sheet_downloaded', null=True, verbose_name='Answer sheets downloaded manually by teacher')),
                ('school', models.ForeignKey(db_column='School', on_delete=apps.competition.models._on_delete, to='competition.school')),
            ],
            options={
                'ordering': ['school', 'surname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateField(blank=True, db_column='Date_Archived', null=True, verbose_name='Date Archived')),
                ('firstname', models.CharField(db_column='First_name', max_length=255, verbose_name='First name')),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('phone_primary', models.CharField(blank=True, db_column='Phone (Primary)', max_length=15)),
                ('phone_alt', models.CharField(blank=True, db_column='Phone (Alternative)', max_length=15)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('notes', models.CharField(db_column='Notes', max_length=500)),
                ('location', models.CharField(choices=[('CPT', 'Cape Town'), ('GEO', 'George')], db_column='Location', max_length=3)),
                ('school', models.ForeignKey(db_column='School', on_delete=apps.competition.models._on_delete, to='competition.school')),
                ('venue', models.ForeignKey(blank=True, db_column='Venue', null=True, on_delete=apps.competition.models._on_delete, to='competition.venue')),
            ],
            options={
                'ordering': ['archived', 'school', 'surname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='First_name', max_length=255, verbose_name='First name')),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('phone_primary', models.CharField(blank=True, db_column='Phone (Primary)', max_length=15)),
                ('phone_alt', models.CharField(blank=True, db_column='Phone (Alternative)', max_length=15)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500)),
                ('location', models.CharField(choices=[('CPT', 'Cape Town'), ('GEO', 'George')], db_column='Location', max_length=3)),
                ('school', models.ForeignKey(db_column='School', on_delete=apps.competition.models._on_delete, to='competition.school')),
                ('venue', models.ForeignKey(blank=True, db_column='Venue', null=True, on_delete=apps.competition.models._on_delete, to='competition.venue')),
            ],
            options={
                'ordering': ['school', 'surname', 'firstname'],
            },
        ),
    ]
